version: "3.8"

services:
  personal_blog:
    build: ./app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env-prod
    volumes:
      - .:./usr/src/app/
    ports:
      - 8000:8000
    