version: "3.8"

services:
  personal_blog:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - .:/app/

    ports:
      - 8000:8000
    