version: "3.8"

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    expose:
      - 8000
    volumes:
      - static_volume:/home/www/staticfiles

    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
      - redis
    volumes:
      - static_volume:/home/www/staticfiles

volumes:
  static_volume:
  redis_data: